package com.george.usermanagementapi.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * JPA entity representing a user in the system.
 *
 * <p>Timestamps ({@code createdAt}, {@code updatedAt}) are managed automatically
 * via {@link PrePersist} and {@link PreUpdate} lifecycle callbacks so the
 * application layer never needs to set them manually.
 */
@Entity
@Table(
        name = "users",
        uniqueConstraints = @UniqueConstraint(name = "uk_users_email", columnNames = "email")
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Primary key — auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User's given name. Never null or blank. */
    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    /** User's family name. Never null or blank. */
    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;

    /** Unique email address used for identification. */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /** Optional contact phone number. */
    @Column(name = "phone_number", length = 20)
    private String phoneNumber;

    /** Set once when the record is first persisted. Never updated after that. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Updated every time the record is saved. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Runs before the first INSERT.
     * Sets both {@code createdAt} and {@code updatedAt} to the current instant.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Runs before every subsequent UPDATE.
     * Refreshes {@code updatedAt} to the current instant.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
